import { motion } from 'framer-motion';
import { ArrowLeft, Download, ShieldCheck } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import ScoreCard from '../components/ScoreCard';
import RecommendationCard from '../components/RecommendationCard';

export default function Dashboard({ data, onBack }) {
  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0f1115]">
        <button onClick={onBack} className="text-brand-400 hover:text-brand-300">Return Home</button>
      </div>
    );
  }

  const { overallScore, homepageScore, pdpScore, cartScore, collectionScore, recommendations = [], experiments = [] } = data;

  // Prepare data for Impact chart
  const impactCount = recommendations.reduce((acc, curr) => {
    const impact = curr.impact?.toLowerCase() || 'low';
    acc[impact] = (acc[impact] || 0) + 1;
    return acc;
  }, { high: 0, medium: 0, low: 0 });

  const chartData = [
    { name: 'High', count: impactCount.high, color: '#4ade80' },
    { name: 'Medium', count: impactCount.medium, color: '#facc15' },
    { name: 'Low', count: impactCount.low, color: '#9ca3af' },
  ];

  const handleExport = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(data, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", "cro_audit.json");
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  return (
    <div className="min-h-screen bg-[#0f1115] text-gray-100 p-6 md:p-12">
      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* Header */}
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 glass-panel p-6">
          <div className="flex items-center gap-4">
            <button 
              onClick={onBack}
              className="p-2 hover:bg-white/10 rounded-lg transition-colors"
            >
              <ArrowLeft size={24} />
            </button>
            <div>
              <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                <ShieldCheck className="text-brand-400" /> CRO Audit Results
              </h1>
              <p className="text-sm text-gray-400 mt-1">Generated by AI Opportunity Engine</p>
            </div>
          </div>
          <button 
            onClick={handleExport}
            className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 px-4 py-2 rounded-lg transition-colors text-sm font-medium"
          >
            <Download size={16} /> Export Report
          </button>
        </header>

        {/* Scores Section */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div className="col-span-2 md:col-span-1">
            <ScoreCard title="Overall Score" score={overallScore} type="overall" />
          </div>
          <ScoreCard title="Homepage" score={homepageScore} />
          <ScoreCard title="Product Pages" score={pdpScore} />
          <ScoreCard title="Collections" score={collectionScore} />
          <ScoreCard title="Cart & Checkout" score={cartScore} />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Chart Section */}
          <div className="glass-panel p-6 lg:col-span-1 flex flex-col">
            <h3 className="text-lg font-semibold mb-6">Impact Distribution</h3>
            <div className="flex-1 min-h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" vertical={false} />
                  <XAxis dataKey="name" stroke="#9ca3af" tick={{fill: '#9ca3af'}} axisLine={false} tickLine={false} />
                  <YAxis stroke="#9ca3af" tick={{fill: '#9ca3af'}} axisLine={false} tickLine={false} />
                  <Tooltip 
                    cursor={{fill: '#1f2937'}}
                    contentStyle={{backgroundColor: '#111827', borderColor: '#374151', borderRadius: '8px'}}
                  />
                  <Bar dataKey="count" radius={[4, 4, 0, 0]}>
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Recommendations List */}
          <div className="lg:col-span-2 space-y-4">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xl font-semibold">Prioritized Recommendations</h3>
              <span className="text-sm text-gray-400">{recommendations.length} items found</span>
            </div>
            
            <div className="space-y-4">
              {recommendations.map((rec, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <RecommendationCard 
                    rec={rec} 
                    experiment={experiments[index]} 
                  />
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
